services:
  site:
    image: img-proc-site
    build: ./site
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - img-proc-net
  api:
    image: img-proc-api
    build: ./api
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - img-proc-uploads:/mnt/uploads:rw
    networks:
      - img-proc-net
    secrets:
      - mongodb_url
    environment:
      - APP_PORT=8080
      - MONGODB_URL_FILE=/run/secrets/mongodb_url
      - DB_NAME=imgproc
      - RABBITMQ_URL=amqp://rabbitmq
      - UPLOADS_PATH=/mnt/uploads
  rabbitmq:
    image: rabbitmq:management
    expose:
      - "5672"
    ports:
      - "15672:15672"
    networks:
      - img-proc-net
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
secrets:
  mongodb_url:
    file: mongodb_url.txt
volumes:
  img-proc-uploads:
    external: true
networks:
  img-proc-net:
    name: img-proc-net
    external: true
