services:
  api:
    image: img-proc-api
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - uploads:/mnt/uploads:rw
    networks:
      - img-proc-net
    environment:
      - APP_PORT=8080
      - DB_HOST=postgres-dev
      - DB_PORT=5432
      - DB_NAME=imgproc
      - DB_USER=postgres
      - DB_PASSWORD=Welcome$
      - UPLOADS_PATH=/mnt/uploads
  site:
    image: img-proc-site
    build: ./site
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - img-proc-net
  rabbitmq:
    image: rabbitmq
    networks:
      - img-proc-net
volumes:
  uploads:
networks:
  img-proc-net:
    name: img-proc-net
    external: true
